.TH SIT-DEATH 1 sit\-%VERSION%
.SH NAME
sit-death \- %DESCRIPTION%
.SH SYNOPSIS
.B sit death
.IR command
.IR [option...]
.IR ticket-id
[--]
.IR [unix-timestamp]
.SH COMMANDS
.TP
.B set
Set the time (in seconds since Epoch) when
the issue was closed.
.TP
.B get
Get the time when the issue was closed.
.SH OPTIONS
.TP
.B \-f
Force the time to be set if their is not time
already set. Note that this will close the ticket,
and that closed tickets cannot be reopened.
Only usable with \fBset\fP.
.TP
.B \-p
Print ticket's ID at the beginning of the line.
Only usable with \fBget\fP.
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH BUGS
Please report them.

