.TH SIT-STATUS 1 sit\-%VERSION%
.SH NAME
sit-status \- %DESCRIPTION%
.SH SYNOPSIS
.B sit status
.IR [command]
.IR [option...]
.IR [ticket-id]
[--]
.IR [status]
.SH COMMANDS
.TP
(none)
Get the status of the issue tracker.
.TP
.B set
Set the status of the issue.
.TP
.B get
Get the status of the issue.
.SH OPTIONS
.TP
.B \-p
Print ticket's ID at the beginning of the line.
Only usable with \fBget\fP.
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH BUGS
Please report them.

