.TH SIT-DUPLICATE 1 sit\-%VERSION%
.SH NAME
sit-duplicate \- %DESCRIPTION%
.SH SYNOPSIS
.B sit duplicate
.IR id-of-duplicate-ticket
.IR id-of-original-ticket
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH BUGS
Please report them.

