.TH SIT-TITLE 1 sit\-%VERSION%
.SH NAME
sit-title \- %DESCRIPTION%
.SH SYNOPSIS
.B sit title
.IR command
.IR [option...]
.IR ticket-id
[--]
.IR [title]
.SH COMMANDS
.TP
.B set
Set the title of the issue.
.TP
.B get
Get the title of the issue.
.SH OPTIONS
.TP
.B \-p
Print ticket's ID at the beginning of the line.
Only usable with \fBget\fP.
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH BUGS
Please report them.

